/**
 * Generated by Copilot.
 * 
 * Not even GitHub Copilot, just the regular Copilot chat.
 * Reviewed by a human who did a lot of copy pasting.
 * 
 * This plugin is what happens when you are a complete beginner trying
 * to cook some Arch rice - but you don't trust 3rd party libraries.
 * 
 * And also because nothing seemed efficient enough for my needs. * 
 */

#include <QtQml/QQmlExtensionPlugin>
#include <QtQml/qqml.h> 
#include "NetworkMonitor.h"
#include "NetworkControl.h"

static QObject* network_control_singleton_provider(QQmlEngine *engine, QJSEngine *scriptEngine) {
    Q_UNUSED(engine)
    Q_UNUSED(scriptEngine)
    
    // The engine takes ownership of this object
    return new NetworkControl();
}

static QObject* network_monitor_singleton_provider(QQmlEngine *engine, QJSEngine *scriptEngine) {
    Q_UNUSED(engine)
    Q_UNUSED(scriptEngine)
    
    // The engine takes ownership of this object
    return new NetworkMonitor();
}

class NetworkMonitorDBusPlugin : public QQmlExtensionPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlExtensionInterface_iid)

public:
    void registerTypes(const char *uri) override {
        // 1. Register NetworkMonitor as a Singleton
        qmlRegisterSingletonType<NetworkMonitor>(uri, 1, 0, "NetworkMonitor", network_monitor_singleton_provider);

        // 2. Register NetworkControl as a Singleton
        qmlRegisterSingletonType<NetworkControl>(uri, 1, 0, "NetworkControl", network_control_singleton_provider);
    }
};

#include "plugin.moc"