/**
 * Generated by Copilot.
 * 
 * Not even GitHub Copilot, just the regular Copilot chat.
 * Reviewed by a human who did a lot of copy pasting.
 * 
 * This plugin is what happens when you are a complete beginner trying
 * to cook some Arch rice - but you don't trust 3rd party libraries.
 * 
 * And also because nothing seemed efficient enough for my needs. * 
 */

#include <QtQml/QQmlExtensionPlugin>
#include <QtQml/qqml.h> 
#include "NetworkMonitor.h"
#include "NetworkControl.h"

class NetworkMonitorDBusPlugin : public QQmlExtensionPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlExtensionInterface_iid)

public:
    void registerTypes(const char *uri) override {
        qmlRegisterType<NetworkMonitor>(uri, 1, 0, "NetworkMonitor");
        qmlRegisterType<NetworkControl>(uri, 1, 0, "NetworkControl");
    }
};

#include "plugin.moc"