/**
 * Generated by AI.
 * 
 * Not even GitHub Copilot or some fancy coding AI.
 * Just the regular chat versions.
 * 
 * Reviewed by a human who did a lot of copy pasting.
 * 
 * This plugin is what happens when you are a complete beginner trying
 * to cook some Arch rice - but you don't trust 3rd party libraries.
 * 
 * And also because nothing seemed efficient enough for my needs.
 * 
 * I make no claims and offer no guarantees on the quality of this plugin.
 * In fact, I waive all liabilities.
 * 
 * Just, find something else really.
 */

#include <QtQml/QQmlExtensionPlugin>
#include <QtQml/qqml.h> 
#include "NetworkMonitor.h"
#include "NetworkControl.h"
#include "DBusFactory.h"

class NetworkMonitorPlugin : public QQmlExtensionPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlExtensionInterface_iid)

    public:
        void registerTypes(const char *uri) override {
            qmlRegisterType<NetworkMonitor>(uri, 1, 0, "NetworkMonitor");
            qmlRegisterType<NetworkControl>(uri, 1, 0, "NetworkControl");
        }

        ~NetworkMonitorPlugin() {
            DBusFactory::cleanup();  // Clean up shared DBus resources
        }
};

#include "plugin.moc"